---
interface:
  - name: ethernet-1/1
    admin-state: enable
    subinterface:
      - index: 0
        ipv4:
          address:
            - ip-prefix: 192.168.11.2/30
  - name: ethernet-1/2
    admin-state: enable
    subinterface:
      - index: 0
        ipv4:
          address:
            - ip-prefix: 192.168.12.2/30
  - name: system0
    admin-state: enable
    subinterface:
      - index: 0
        ipv4:
          address:
            - ip-prefix: 10.0.1.1/32

routing-policy:
  policy:
    - name: all
      default-action:
        policy-result: accept

network-instance:
  - name: default
    admin-state: enable
    interface:
      - name: ethernet-1/1.0
      - name: ethernet-1/2.0
      - name: system0.0
    protocols:
      bgp:
        admin-state: enable
        autonomous-system: 201
        router-id: 10.0.1.1
        afi-safi:
          - afi-safi-name: ipv4-unicast
            admin-state: enable
        group:
          - group-name: eBGP-underlay
            admin-state: enable
            export-policy: all
            import-policy: all
