---
srl_nokia-interfaces:interface:
  # az1 leaves
  - name: ethernet-1/3
    admin-state: enable
    description: "CORE: cr2_e1/1..az1lf1_e-1/55"
    subinterface:
      - index: 0
        type: routed
        ipv4:
          admin-state: enable
          address:
            # 169.254.20{core}{next_avail_lower}/30
            - ip-prefix: 169.254.202.1/30
  - name: ethernet-1/4
    admin-state: enable
    description: "CORE: cr2_e1/2..az1lf2_e-1/55"
    subinterface:
      - index: 0
        type: routed
        ipv4:
          admin-state: enable
          address:
            # 169.254.20{core}{next_avail_lower}/30
            - ip-prefix: 169.254.202.5/30
  - name: ethernet-1/5
    admin-state: enable
    description: "CORE: cr2_e1/3..az1lf3_e-1/55"
    subinterface:
      - index: 0
        type: routed
        ipv4:
          admin-state: enable
          address:
            # 169.254.20{core}{next_avail_lower}/30
            - ip-prefix: 169.254.202.9/30
  - name: ethernet-1/6
    admin-state: enable
    description: "CORE: cr2_e1/4..az1lf4_e-1/55"
    subinterface:
      - index: 0
        type: routed
        ipv4:
          admin-state: enable
          address:
            # 169.254.20{core}{next_avail_lower}/30
            - ip-prefix: 169.254.202.13/30
  - name: ethernet-1/7
    admin-state: enable
    description: "CORE: cr2_e1/5..az1lf5_e-1/55"
    subinterface:
      - index: 0
        type: routed
        ipv4:
          admin-state: enable
          address:
            # 169.254.20{core}{next_avail_lower}/30
            - ip-prefix: 169.254.202.17/30
  - name: ethernet-1/8
    admin-state: enable
    description: "CORE: cr2_e1/8..az1lf6_e-1/55"
    subinterface:
      - index: 0
        type: routed
        ipv4:
          admin-state: enable
          address:
            # 169.254.20{core}.{next_avail_lower}/30
            - ip-prefix: 169.254.202.21/30
  # Edge
  - name: ethernet-1/10
    admin-state: enable
    description: "EDGE: cr2_e1/10..ed1_eth2"
    subinterface:
      - index: 0
        type: routed
        ipv4:
          admin-state: enable
          address:
            # 169.254.21{core}.{next_avail_lower}/30
            - ip-prefix: 169.254.212.1/30
  - name: ethernet-1/11
    admin-state: enable
    description: "EDGE: cr2_e1/11..ed2_eth2"
    subinterface:
      - index: 0
        type: routed
        ipv4:
          admin-state: enable
          address:
            # 169.254.21{core}.{next_avail_lower}/30
            - ip-prefix: 169.254.212.5/30
  # Loopback
  - name: system0
    admin-state: enable
    subinterface:
      - index: 0
        ipv4:
          admin-state: enable
          address:
            # 169.254.7.{corenumber}/32
            - ip-prefix: 169.254.7.2/32
srl_nokia-network-instance:network-instance:
  - name: WAN_EDGE
    admin-state: enable
    interface:
      - name: ethernet-1/10.0
      - name: ethernet-1/11.0
      - name: system0.0
    protocols:
      bgp:
        autonomous-system: 65999
        router-id: 169.254.7.2
        afi-safi:
          - afi-safi-name: ipv4-unicast
            admin-state: enable
            multipath:
              max-paths-level-1: 8
              max-paths-level-2: 8
        group:
          - group-name: ebgp_edge
            admin-state: enable
            export-policy: ebgp_export_edge
            import-policy: ebgp_import_edge
            graceful-restart:
              admin-state: enable
            trace-options:
              flag:
                - name: events
                - name: graceful-restart
            timers:
              connect-retry: 1
              hold-time: 9
              keepalive-interval: 3
              minimum-advertisement-interval: 1
        neighbor:
          - peer-address: 169.254.212.2
            peer-as: 62371
            peer-group: ebgp_edge
          - peer-address: 169.254.212.6
            peer-as: 62371
            peer-group: ebgp_edge
  - name: Routing
    admin-state: enable
    type: ip-vrf
    interface:
      - name: ethernet-1/3.0
      - name: ethernet-1/4.0
      - name: ethernet-1/5.0
      - name: ethernet-1/6.0
      - name: ethernet-1/7.0
      - name: ethernet-1/8.0
    protocols:
      bgp:
        autonomous-system: 65008
        router-id: 169.254.7.2
        afi-safi:
          - afi-safi-name: ipv4-unicast
            admin-state: enable
        group:
          - group-name: ebgp_fabric
            admin-state: enable
            # timers:
            #   connect-retry: 1
            #   hold-time: 9
            #   keepalive-interval: 3
            #   minimum-advertisement-interval: 1
        neighbor:
          - peer-address: 169.254.202.2
            peer-group: ebgp_fabric
            peer-as: 65001
          - peer-address: 169.254.202.6
            peer-group: ebgp_fabric
            peer-as: 65002
          - peer-address: 169.254.202.10
            peer-group: ebgp_fabric
            peer-as: 65003
          - peer-address: 169.254.202.14
            peer-group: ebgp_fabric
            peer-as: 65004
          - peer-address: 169.254.202.18
            peer-group: ebgp_fabric
            peer-as: 65005
          - peer-address: 169.254.202.22
            peer-group: ebgp_fabric
            peer-as: 65006
srl_nokia-routing-policy:routing-policy:
  prefix-set:
    - name: WAN_EDGE_loopbacks
      prefix:
        - ip-prefix: "169.254.1.253/32"
          mask-length-range: "32..32"
        - ip-prefix: "169.254.2.253/32"
          mask-length-range: "32..32"
        - ip-prefix: "169.254.3.253/32"
          mask-length-range: "32..32"
        - ip-prefix: "169.254.1.252/32"
          mask-length-range: "32..32"
        - ip-prefix: "169.254.2.252/32"
          mask-length-range: "32..32"
    - name: default_route
      prefix:
        - ip-prefix: "0.0.0.0/0"
          mask-length-range: "32..32"
    - name: proton_public
      prefix:
        - ip-prefix: "185.70.40.0/22"
          mask-length-range: "32..32"
  policy:
    - name: ebgp_import_edge
      statement:
        - name: accept-wan-edge-loopbacks
          match:
            prefix-set: WAN_EDGE_loopbacks
            family:
              - ipv4-unicast
          action:
            policy-result: accept
        - name: accept-default-route
          match:
            prefix-set: default_route
            family:
              - ipv4-unicast
          action:
            policy-result: accept
        - name: default-reject
          action:
            policy-result: reject
    - name: ebgp_export_edge
      statement:
        - name: accept-local-proton-public-prefixes
          match:
            prefix-set: proton_public
            protocol: local
            family:
              - ipv4-unicast
          action:
            policy-result: accept
        - name: accept-bgp-proton-public-prefixes
          match:
            prefix-set: proton_public
            protocol: bgp
            family:
              - ipv4-unicast
          action:
            policy-result: accept
        - name: accept-evpn-proton-public-prefixes
          match:
            prefix-set: proton_public
            protocol: bgp-evpn
            family:
              - ipv4-unicast
          action:
            policy-result: accept
        - name: default-reject
          action:
            policy-result: reject
