---
srl_nokia-interfaces:interface:
  # SPINES!
  - name: ethernet-1/49
    admin-state: enable
    description: "CORE: az1sp01_e1/2..az1lf02_e-1/49"
    subinterface:
      - index: 0
        type: routed
        ipv4:
          admin-state: enable
          address:
            # 169.254.{spine}{next_avail_upper}/30
            - ip-prefix: 169.254.1.6/30
  - name: ethernet-1/50
    admin-state: enable
    description: "CORE: az1sp02_e1/2..az1lf02_e-1/50"
    subinterface:
      - index: 0
        type: routed
        ipv4:
          admin-state: enable
          address:
            # 169.254.{spine}{next_avail_upper}/30
            - ip-prefix: 169.254.2.6/30
  - name: ethernet-1/51
    admin-state: enable
    description: "CORE: az1sp03_e1/3..az1lf02_e-1/51"
    subinterface:
      - index: 0
        type: routed
        ipv4:
          admin-state: enable
          address:
            # 169.254.{spine}{next_avail_upper}/30
            - ip-prefix: 169.254.3.6/30
  # CORES!
  - name: ethernet-1/54
    admin-state: enable
    description: "CORE: az1lf2_e-1/54..cr3_e1/4"
    subinterface:
      - index: 0
        type: routed
        ipv4:
          admin-state: enable
          address:
            # 169.254.20{core}{next_avail_upper}/30
            - ip-prefix: 169.254.203.6/30
  - name: ethernet-1/55
    admin-state: enable
    description: "CORE: az1lf2_e-1/55..cr2_e1/4"
    subinterface:
      - index: 0
        type: routed
        ipv4:
          admin-state: enable
          address:
            # 169.254.20{core}{next_avail_upper}/30
            - ip-prefix: 169.254.202.6/30
  - name: ethernet-1/56
    admin-state: enable
    description: "CORE: az1lf2_e-1/56..cr1_e1/4"
    subinterface:
      - index: 0
        type: routed
        ipv4:
          admin-state: enable
          address:
            # 169.254.20{core}{next_avail_upper}/30
            - ip-prefix: 169.254.201.6/30
  # LOOPBACK!
  - name: system0
    admin-state: enable
    subinterface:
      - index: 0
        ipv4:
          admin-state: enable
          address:
            # 169.254.{devnum}.{254_lf|255_sp}/32
            - ip-prefix: 169.254.2.254/32
  - name: irb1
    admin-state: enable
    subinterface:
      - index: 0
        ipv4:
          admin-state: enable
          address:
            - ip-prefix: 192.168.0.1/25
              anycast-gw: true
          arp:
            learn-unsolicited: true
            evpn:
              advertise:
                - route-type: dynamic
        anycast-gw:
          virtual-router-id: 1
      - index: 200
        ipv4:
          admin-state: enable
          address:
            - ip-prefix: 10.200.200.1/24
              anycast-gw: true
          arp:
            learn-unsolicited: true
            evpn:
              advertise:
                - route-type: dynamic
            host-route:
              populate:
                - route-type: static
                  datapath-programming: true
                - route-type: dynamic
                  datapath-programming: true
        anycast-gw:
          virtual-router-id: 21
      - index: 500
        ipv4:
          admin-state: enable
          address:
            - ip-prefix: 172.16.50.1/24
              anycast-gw: true
          arp:
            learn-unsolicited: true
            evpn:
              advertise:
                - route-type: dynamic
            host-route:
              populate:
                - route-type: static
                  datapath-programming: true
                - route-type: dynamic
                  datapath-programming: true
        anycast-gw:
          virtual-router-id: 51
      - index: 900
        ipv4:
          admin-state: enable
          address:
            - ip-prefix: 172.16.0.1/24
              anycast-gw: true
          arp:
            learn-unsolicited: true
            evpn:
              advertise:
                - route-type: dynamic
        anycast-gw:
          virtual-router-id: 22
tunnel-interface:
  - name: vxlan1
    vxlan-interface:
      # MGMT_Infra_VLAN_untagged
      - index: 0
        type: bridged
        ingress:
          vni: 1
        egress:
          source-ip: use-system-ipv4-address
      # FE_VLAN_200
      - index: 200
        type: bridged
        ingress:
          vni: 200
        egress:
          source-ip: use-system-ipv4-address
      # BE_VLAN_500
      - index: 500
        type: bridged
        ingress:
          vni: 500
        egress:
          source-ip: use-system-ipv4-address
      # FE_VLAN_900
      - index: 900
        type: bridged
        ingress:
          vni: 900
        egress:
          source-ip: use-system-ipv4-address
      # MGMT_Infra_L3
      - index: 10000
        type: routed
        ingress:
          vni: 10000
        egress:
          source-ip: use-system-ipv4-address
      # FrontEnd_L3
      - index: 10200
        type: routed
        ingress:
          vni: 10200
        egress:
          source-ip: use-system-ipv4-address
      # BackEnd_L3
      - index: 10500
        type: routed
        ingress:
          vni: 10500
        egress:
          source-ip: use-system-ipv4-address
system:
  network-instance:
    protocols:
      evpn:
        ethernet-segments:
          bgp-instance:
            - id: 1
              ethernet-segment:
                - name: cab1-websrv1_bond0
                  admin-state: enable
                  esi: 00:12:12:12:12:12:12:00:00:01
                  interface:
                    - ethernet-interface: lag1
                - name: cab1-hapsrv1_bond0
                  admin-state: enable
                  esi: 00:12:12:12:12:12:12:00:00:02
                  interface:
                    - ethernet-interface: lag2
                - name: cab1-dbsrv1_bond0
                  admin-state: enable
                  esi: 00:12:12:12:12:12:12:00:00:03
                  interface:
                    - ethernet-interface: lag3
      bgp-vpn:
        bgp-instance:
          - id: 1
