---
srl_nokia-network-instance:network-instance:
  ## L3
  - name: MGMT_INFRA_L3
    type: ip-vrf
    admin-state: enable
    interface:
      - name: irb1.0
    vxlan-interface:
      - name: vxlan1.10000
    protocols:
      bgp-evpn:
        bgp-instance:
          - id: 1
            admin-state: enable
            vxlan-interface: vxlan1.10000
            evi: 10000
            ecmp: 3
      bgp-vpn:
        bgp-instance:
          - id: 1
            route-target:
              export-rt: target:1:10000
              import-rt: target:1:10000
  ## L2
  # Untagged vlan 1
  - name: MGMT_Infra_VLAN_1
    type: mac-vrf
    admin-state: enable
    interface:
      - name: irb1.0
      - name: lag1.0
      - name: lag2.0
      - name: lag3.0
    vxlan-interface:
      - name: vxlan1.0
    protocols:
      bgp-evpn:
        bgp-instance:
          - id: 1
            admin-state: enable
            vxlan-interface: vxlan1.0
            evi: 1
            ecmp: 3
      bgp-vpn:
        bgp-instance:
          - id: 1
            route-target:
              export-rt: target:1:1
              import-rt: target:1:1
