---
srl_nokia-interfaces:interface:
  - name: irb1
    admin-state: enable
    subinterface:
      - index: 0
        ipv4:
          admin-state: enable
          address:
            - ip-prefix: 192.168.0.1/25
              anycast-gw: true
          arp:
            learn-unsolicited: true
            evpn:
              advertise:
                - route-type: dynamic
        anycast-gw:
          virtual-router-id: 1
      - index: 200
        ipv4:
          admin-state: enable
          address:
            - ip-prefix: 10.200.200.1/24
              anycast-gw: true
          arp:
            learn-unsolicited: true
            evpn:
              advertise:
                - route-type: dynamic
            host-route:
              populate:
                - route-type: static
                  datapath-programming: true
                - route-type: dynamic
                  datapath-programming: true
        anycast-gw:
          virtual-router-id: 21
      - index: 500
        ipv4:
          admin-state: enable
          address:
            - ip-prefix: 172.16.50.1/24
              anycast-gw: true
          arp:
            learn-unsolicited: true
            evpn:
              advertise:
                - route-type: dynamic
            host-route:
              populate:
                - route-type: static
                  datapath-programming: true
                - route-type: dynamic
                  datapath-programming: true
        anycast-gw:
          virtual-router-id: 51
      - index: 900
        ipv4:
          admin-state: enable
          address:
            - ip-prefix: 172.16.0.1/24
              anycast-gw: true
          arp:
            learn-unsolicited: true
            evpn:
              advertise:
                - route-type: dynamic
        anycast-gw:
          virtual-router-id: 22
