---
srl_nokia-interfaces:interface:
  # LAGS!
  - name: lag1
    admin-state: enable
    description: "SRV: cab3-websrv3_eth1"
    vlan-tagging: true
    subinterface:
      - index: 0
        type: bridged
        admin-state: enable
        vlan:
          encap:
            untagged: {}
      - index: 200
        type: bridged
        admin-state: enable
        vlan:
          encap:
            single-tagged:
              vlan-id: 200
    lag:
      lag-type: lacp
      member-speed: 25G
      lacp:
        interval: FAST
        lacp-mode: ACTIVE
        admin-key: 1
        system-id-mac: 02:00:00:05:06:01
  - name: lag2
    admin-state: enable
    description: "SRV: cab3-hapsrv3_eth1"
    vlan-tagging: true
    subinterface:
      - index: 0
        type: bridged
        admin-state: enable
        vlan:
          encap:
            untagged: {}
      - index: 900
        type: bridged
        admin-state: enable
        vlan:
          encap:
            single-tagged:
              vlan-id: 900
    lag:
      lag-type: lacp
      member-speed: 25G
      lacp:
        interval: FAST
        lacp-mode: ACTIVE
        admin-key: 2
        system-id-mac: 02:00:00:05:06:02
  - name: lag3
    admin-state: enable
    description: "SRV: cab3-dbsrv3_eth1"
    vlan-tagging: true
    subinterface:
      - index: 0
        type: bridged
        admin-state: enable
        vlan:
          encap:
            untagged: {}
      - index: 500
        type: bridged
        admin-state: enable
        vlan:
          encap:
            single-tagged:
              vlan-id: 500
    lag:
      lag-type: lacp
      member-speed: 25G
      lacp:
        interval: FAST
        lacp-mode: ACTIVE
        admin-key: 3
        system-id-mac: 02:00:00:05:06:03
  # PORTS!
  - name: ethernet-1/1
    admin-state: enable
    description: "SRV: cab3-websrv3_bond0"
    ethernet:
      aggregate-id: lag1
      reload-delay: 20
  - name: ethernet-1/2
    admin-state: enable
    description: "SRV: cab3-hapsrv3_bond0"
    ethernet:
      aggregate-id: lag2
      reload-delay: 20
  - name: ethernet-1/3
    admin-state: enable
    description: "SRV: cab3-dbsrv3_bond0"
    ethernet:
      aggregate-id: lag3
      reload-delay: 20
