srl_nokia-network-instance:network-instance:
  ## L3
  - name: BackEnd
    type: ip-vrf
    admin-state: enable
    interface:
      - name: irb1.500
    vxlan-interface:
      - name: vxlan1.10500
    protocols:
      bgp-evpn:
        bgp-instance:
          - id: 1
            admin-state: enable
            vxlan-interface: vxlan1.10500
            evi: 10500
            ecmp: 3
      bgp-vpn:
        bgp-instance:
          - id: 1
            route-target:
              export-rt: target:1:10500
              import-rt: target:1:10500
    inter-instance-policies:
      apply-policy:
        import-policy: VRF_Leak_FE_BE
        export-policy: VRF_Leak_BE_FE
  ## L2
  # vlan 500 (mysql)
  - name: BE_VLAN_500
    type: mac-vrf
    admin-state: enable
    interface:
      - name: irb1.500
      - name: lag3.500
    vxlan-interface:
      - name: vxlan1.500
    protocols:
      bgp-evpn:
        bgp-instance:
          - id: 1
            admin-state: enable
            vxlan-interface: vxlan1.500
            evi: 500
            ecmp: 3
      bgp-vpn:
        bgp-instance:
          - id: 1
            route-target:
              export-rt: target:1:500
              import-rt: target:1:500
  