---
srl_nokia-interfaces:interface:
  - name: ethernet-1/1
    admin-state: enable
    description: "CORE: az1sp01_e1/1..az1lf02_e-1/49"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.{spine}{next_avail_lower}/30
            - ip-prefix: 169.254.1.1/30
  - name: ethernet-1/2
    admin-state: enable
    description: "CORE: az1sp01_e1/2..az1lf02_e-1/49"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.{spine}{next_avail_lower}/30
            - ip-prefix: 169.254.1.5/30
  - name: ethernet-1/3
    admin-state: enable
    description: "CORE: az1sp01_e1/3..az1lf03_e-1/49"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.{spine}{next_avail_lower}/30
            - ip-prefix: 169.254.1.9/30
  - name: ethernet-1/4
    admin-state: enable
    description: "CORE: az1sp01_e1/4..az1lf04_e-1/49"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.{spine}{next_avail_lower}/30
            - ip-prefix: 169.254.1.13/30
  - name: ethernet-1/5
    admin-state: enable
    description: "CORE: az1sp01_e1/5..az1lf05_e-1/49"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.{spine}{next_avail_lower}/30
            - ip-prefix: 169.254.1.17/30
  - name: ethernet-1/6
    admin-state: enable
    description: "CORE: az1sp01_e1/6..az1lf06_e-1/49"
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.{spine}{next_avail_lower}/30
            - ip-prefix: 169.254.1.21/30
  - name: system0
    admin-state: enable
    subinterface:
      - index: 0
        ipv4:
          address:
            # 169.254.{devnum}.{254_lf|255_sp}/32
            - ip-prefix: 169.254.1.255/32
srl_nokia-network-instance:network-instance:
  - name: default
    admin-state: enable
    interface:
      - name: ethernet-1/1.0
      - name: ethernet-1/2.0
      - name: ethernet-1/3.0
      - name: ethernet-1/4.0
      - name: ethernet-1/5.0
      - name: ethernet-1/6.0
      - name: system0.0
    protocols:
      bgp:
        autonomous-system: 65000
        router-id: 169.254.1.255
        afi-safi:
          - afi-safi-name: ipv4-unicast
            admin-state: enable
            multipath:
              max-paths-level-1: 8
              max-paths-level-2: 8
        group:
          - group-name: underlay
            admin-state: enable
            export-policy: underlay-loopback-out
            import-policy: underlay-loopback-in
            graceful-restart:
              admin-state: enable
            trace-options:
              flag:
                - name: events
                - name: graceful-restart
            timers:
              connect-retry: 1
              hold-time: 9
              keepalive-interval: 3
              minimum-advertisement-interval: 1
          - group-name: overlay-fabric
            peer-as: 64999
            local-as:
              as-number: 64999
            transport:
              local-address: 169.254.1.255
            admin-state: enable
            afi-safi:
              - afi-safi-name: evpn
                admin-state: enable
            route-reflector:
              client: true
              cluster-id: 169.254.0.255
            timers:
              connect-retry: 1
              hold-time: 9
              keepalive-interval: 3
              minimum-advertisement-interval: 1
        neighbor:
          - peer-address: 169.254.1.2
            peer-as: 65001
            peer-group: underlay
          - peer-address: 169.254.1.6
            peer-as: 65002
            peer-group: underlay
          - peer-address: 169.254.1.10
            peer-as: 65003
            peer-group: underlay
          - peer-address: 169.254.1.14
            peer-as: 65004
            peer-group: underlay
          - peer-address: 169.254.1.18
            peer-as: 65005
            peer-group: underlay
          - peer-address: 169.254.1.22
            peer-as: 65006
            peer-group: underlay
          - peer-address: 169.254.1.254
            peer-group: overlay-fabric
          - peer-address: 169.254.2.254
            peer-group: overlay-fabric
          - peer-address: 169.254.3.254
            peer-group: overlay-fabric
          - peer-address: 169.254.4.254
            peer-group: overlay-fabric
          - peer-address: 169.254.5.254
            peer-group: overlay-fabric
          - peer-address: 169.254.6.254
            peer-group: overlay-fabric
srl_nokia-routing-policy:routing-policy:
  prefix-set:
    - name: underlay-loopback-v4
      prefix:
        - ip-prefix: "169.254.0.0/16"
          mask-length-range: "32..32"
  policy:
    - name: underlay-loopback-out
      statement:
        - name: accept-local-loopbacks
          match:
            prefix-set: underlay-loopback-v4
            protocol: local
            family:
              - ipv4-unicast
          action:
            policy-result: accept
        - name: accept-bgp-learned-loopbacks
          match:
            prefix-set: underlay-loopback-v4
            protocol: bgp
            family:
              - ipv4-unicast
          action:
            policy-result: accept
        - name: default-reject
          action:
            policy-result: reject
    - name: underlay-loopback-in
      statement:
        - name: accept-bgp-learned-loopbacks
          match:
            prefix-set: underlay-loopback-v4
            protocol: bgp
            family:
              - ipv4-unicast
          action:
            policy-result: accept
        - name: reject-local-loopbacks
          match:
            prefix-set: underlay-loopback-v4
            protocol: local
            family:
              - ipv4-unicast
          action:
            policy-result: reject
        - name: default-reject
          action:
            policy-result: reject
