---
srl_nokia-interfaces:interface:
  # LAGS!
  - name: lag1
    admin-state: enable
    description: "SRV: cab1-websrv1_eth1"
    vlan-tagging: true
    subinterface:
      - index: 0
        type: bridged
        admin-state: enable
        vlan:
          encap:
            untagged: {}
      - index: 200
        type: bridged
        admin-state: enable
        vlan:
          encap:
            single-tagged:
              vlan-id: 200
    lag:
      lag-type: lacp
      member-speed: 25G
      lacp:
        interval: FAST
        lacp-mode: ACTIVE
        admin-key: 1
        system-id-mac: 02:00:00:01:02:01
  - name: lag2
    admin-state: enable
    description: "SRV: cab1-hapsrv1_eth1"
    vlan-tagging: true
    subinterface:
      - index: 0
        type: bridged
        admin-state: enable
        vlan:
          encap:
            untagged: {}
      - index: 900
        type: bridged
        admin-state: enable
        vlan:
          encap:
            single-tagged:
              vlan-id: 900
    lag:
      lag-type: lacp
      member-speed: 25G
      lacp:
        interval: FAST
        lacp-mode: ACTIVE
        admin-key: 2
        system-id-mac: 02:00:00:01:02:02
  # PORTS!
  - name: ethernet-1/1
    admin-state: enable
    description: "SRV: cab1-websrv1_bond0"
    ethernet:
      aggregate-id: lag1
      reload-delay: 20
  - name: ethernet-1/2
    admin-state: enable
    description: "SRV: cab1-hapsrv1_bond0"
    ethernet:
      aggregate-id: lag2
      reload-delay: 20  
  # SPINES!
  - name: ethernet-1/49
    admin-state: enable
    description: "CORE: az1sp01_e1/1..az1lf01_e-1/49"
    subinterface:
      - index: 0
        type: routed
        ipv4:
          admin-state: enable
          address:
            # 169.254.{spine}{next_avail_upper}/30
            - ip-prefix: 169.254.1.2/30
  - name: ethernet-1/50
    admin-state: enable
    description: "CORE: az1sp02_e1/1..az1lf01_e-1/50"
    subinterface:
      - index: 0
        type: routed
        ipv4:
          admin-state: enable
          address:
            # 169.254.{spine}{next_avail_upper}/30
            - ip-prefix: 169.254.2.2/30
  - name: ethernet-1/51
    admin-state: enable
    description: "CORE: az1sp03_e1/1..az1lf01_e-1/51"
    subinterface:
      - index: 0
        type: routed
        ipv4:
          admin-state: enable
          address:
            # 169.254.{spine}{next_avail_upper}/30
            - ip-prefix: 169.254.3.2/30
  - name: ethernet-1/54
    admin-state: enable
    description: "CORE: az1lf1_e-1/54..cr3_e1/3"
    subinterface:
      - index: 0
        type: routed
        ipv4:
          admin-state: enable
          address:
            # 169.254.20{core}{next_avail_upper}/30
            - ip-prefix: 169.254.203.2/30
  - name: ethernet-1/55
    admin-state: enable
    description: "CORE: az1lf1_e-1/55..cr2_e1/3"
    subinterface:
      - index: 0
        type: routed
        ipv4:
          admin-state: enable
          address:
            # 169.254.20{core}{next_avail_upper}/30
            - ip-prefix: 169.254.202.2/30
  - name: ethernet-1/56
    admin-state: enable
    description: "CORE: az1lf1_e-1/56..cr1_e1/3"
    subinterface:
      - index: 0
        type: routed
        ipv4:
          admin-state: enable
          address:
            # 169.254.20{core}{next_avail_upper}/30
            - ip-prefix: 169.254.201.2/30
  - name: system0
    admin-state: enable
    subinterface:
      - index: 0
        ipv4:
          admin-state: enable
          address:
            # 169.254.{devnum}.{254_lf|255_sp}/32
            - ip-prefix: 169.254.1.254/32
  - name: irb1
    admin-state: enable
    subinterface:
      - index: 1
        ipv4:
          admin-state: enable
          address:
            - ip-prefix: 192.168.0.1/25
              anycast-gw: true
          arp:
            learn-unsolicited: true
            evpn:
              advertise:
                - route-type: dynamic
        anycast-gw: {}
      - index: 200
        ipv4:
          admin-state: enable
          address:
            - ip-prefix: 10.200.200.1/24
              anycast-gw: true
          arp:
            learn-unsolicited: true
            evpn:
              advertise:
                - route-type: dynamic
        anycast-gw: {}
      - index: 900
        ipv4:
          admin-state: enable
          address:
            - ip-prefix: 172.16.0.1/24
              anycast-gw: true
          arp:
            learn-unsolicited: true
            evpn:
              advertise:
                - route-type: dynamic
        anycast-gw: {}
tunnel-interface:
  - name: vxlan1
    vxlan-interface:
      # MGMT_Infra_VLAN_untagged
      - index: 1
        type: bridged
        ingress:
          vni: 1
      # FE_VLAN_200
      - index: 200
        type: bridged
        ingress:
          vni: 200
      # FE_VLAN_900
      - index: 900
        type: bridged
        ingress:
          vni: 900
      # MGMT_Infra_L3
      - index: 4001001
        type: routed
        ingress:
          vni: 4001001
      # FrontEnd_L3
      - index: 4000200
        type: routed
        ingress:
          vni: 4000200
system:
  network-instance:
    protocols:
      evpn:
        ethernet-segments:
          bgp-instance:
            - id: 1
              ethernet-segment:
                - name: cab1-websrv1_bond0
                  admin-state: enable
                  esi: 00:12:12:12:12:12:12:00:00:01
                  interface:
                    - ethernet-interface: lag1
                - name: cab1-hapsrv1_bond0
                  admin-state: enable
                  esi: 00:12:12:12:12:12:12:00:00:02
                  interface:
                    - ethernet-interface: lag2
      bgp-vpn:
        bgp-instance:
          - id: 1
srl_nokia-network-instance:network-instance:
  - name: default
    admin-state: enable
    interface:
      - name: ethernet-1/49.0
      - name: ethernet-1/50.0
      - name: ethernet-1/51.0
      - name: system0.0
    protocols:
      bgp:
        autonomous-system: 65001
        router-id: 169.254.1.254
        failure-detection:
          fast-failover: true
        afi-safi:
          - afi-safi-name: ipv4-unicast
            admin-state: enable
            multipath:
              max-paths-level-1: 8
              max-paths-level-2: 8
        group:
          - group-name: underlay
            peer-as: 65000
            admin-state: enable
            export-policy: underlay-loopback-out
            import-policy: underlay-loopback-in
            graceful-restart:
              admin-state: enable
            trace-options:
              flag:
                - name: events
                - name: graceful-restart
            timers:
              connect-retry: 1
              hold-time: 9
              keepalive-interval: 3
              minimum-advertisement-interval: 1
          - group-name: overlay-fabric
            peer-as: 64999
            local-as:
              as-number: 64999
            transport:
              local-address: 169.254.1.254
            admin-state: enable
            afi-safi:
              - afi-safi-name: evpn
                admin-state: enable
            timers:
              connect-retry: 1
              hold-time: 9
              keepalive-interval: 3
              minimum-advertisement-interval: 1
        neighbor:
          - peer-address: 169.254.1.1
            peer-group: underlay
          - peer-address: 169.254.2.1
            peer-group: underlay
          - peer-address: 169.254.3.1
            peer-group: underlay
          - peer-address: 169.254.1.255
            peer-group: overlay-fabric
          - peer-address: 169.254.2.255
            peer-group: overlay-fabric
          - peer-address: 169.254.3.255
            peer-group: overlay-fabric
  # Routing instance
  - name: Routing
    admin-state: enable
    type: ip-vrf
    interface:
      - name: ethernet-1/54.0
      - name: ethernet-1/55.0
      - name: ethernet-1/56.0
    protocols:
      bgp:
        autonomous-system: 65001
        router-id: 169.254.1.254
        afi-safi:
          - afi-safi-name: ipv4-unicast
            admin-state: enable
        group:
          - group-name: ebgp_cr
            admin-state: enable
            # timers:
            #   connect-retry: 1
            #   hold-time: 9
            #   keepalive-interval: 3
            #   minimum-advertisement-interval: 1
        neighbor:
          - peer-address: 169.254.201.1
            peer-group: ebgp_cr
            peer-as: 65007
          - peer-address: 169.254.202.1
            peer-group: ebgp_cr
            peer-as: 65008
          - peer-address: 169.254.203.1
            peer-group: ebgp_cr
            peer-as: 65009
  ## VLANs
  # Untagged vlan 1
  - name: MGMT_Infra_VLAN_1
    type: mac-vrf
    admin-state: enable
    interface:
      - name: lag1.0
      - name: irb1.1
    vxlan-interface:
      - name: vxlan1.1
    protocols:
      bgp-evpn:
        bgp-instance:
          - id: 1
            admin-state: enable
            vxlan-interface: vxlan1.1
            evi: 1
            ecmp: 3
      bgp-vpn:
        bgp-instance:
          - id: 1
            route-target:
              export-rt: target:1:1
              import-rt: target:1:1
  # vlan 200 (web servers)
  - name: FE_VLAN_200
    type: mac-vrf
    admin-state: enable
    interface:
      - name: lag1.200
      - name: irb1.200
    vxlan-interface:
      - name: vxlan1.200
    protocols:
      bgp-evpn:
        bgp-instance:
          - id: 1
            admin-state: enable
            vxlan-interface: vxlan1.200
            evi: 200
            ecmp: 3
      bgp-vpn:
        bgp-instance:
          - id: 1
            route-target:
              export-rt: target:1:200
              import-rt: target:1:200
  # vlan 900 (HAProxy)
  - name: FE_VLAN_900
    type: mac-vrf
    admin-state: enable
    interface:
      - name: lag2.900
      - name: irb1.900
    vxlan-interface:
      - name: vxlan1.900
    protocols:
      bgp-evpn:
        bgp-instance:
          - id: 1
            admin-state: enable
            vxlan-interface: vxlan1.900
            evi: 900
            ecmp: 3
      bgp-vpn:
        bgp-instance:
          - id: 1
            route-target:
              export-rt: target:1:900
              import-rt: target:1:900
  ## VRFs
  # MGMT Infra VRF
  - name: MGMT_INFRA_L3
    type: ip-vrf
    admin-state: enable
    interface:
      - name: irb1.1
    vxlan-interface:
      - name: vxlan1.4001001
    protocols:
      bgp-evpn:
        bgp-instance:
          - id: 1
            admin-state: enable
            vxlan-interface: vxlan1.4001001
            evi: 10001
            ecmp: 3
      bgp-vpn:
        bgp-instance:
          - id: 1
            route-target:
              export-rt: target:1:4001001
              import-rt: target:1:4001001
  # FrontEnd VRF
  - name: FrontEnd
    type: ip-vrf
    admin-state: enable
    interface:
      - name: irb1.200
      - name: irb1.900
    vxlan-interface:
      - name: vxlan1.4000200
    protocols:
      bgp-evpn:
        bgp-instance:
          - id: 1
            admin-state: enable
            vxlan-interface: vxlan1.4000200
            evi: 10200
            ecmp: 3
      bgp-vpn:
        bgp-instance:
          - id: 1
            route-target:
              export-rt: target:1:4000200
              import-rt: target:1:4000200
      
srl_nokia-routing-policy:routing-policy:
  prefix-set:
    - name: underlay-loopback-v4
      prefix:
        - ip-prefix: "169.254.0.0/16"
          mask-length-range: "32..32"
  policy:
    - name: underlay-loopback-out
      statement:
        - name: accept-local-loopbacks
          match:
            prefix-set: underlay-loopback-v4
            protocol: local
            family:
              - ipv4-unicast
          action:
            policy-result: accept
        - name: reject-bgp-learned-loopbacks
          match:
            prefix-set: underlay-loopback-v4
            protocol: bgp
            family:
              - ipv4-unicast
          action:
            policy-result: reject
        - name: default-reject
          action:
            policy-result: reject
    - name: underlay-loopback-in
      statement:
        - name: accept-bgp-learned-loopbacks
          match:
            prefix-set: underlay-loopback-v4
            protocol: bgp
            family:
              - ipv4-unicast
          action:
            policy-result: accept
        - name: reject-local-loopbacks
          match:
            prefix-set: underlay-loopback-v4
            protocol: local
            family:
              - ipv4-unicast
          action:
            policy-result: reject
        - name: default-reject
          action:
            policy-result: reject
