---
# loopback
system0: 169.254.1.255/32
# Spines
leaves:
  lf1:
    interface: ethernet-1/1
    prefix: 169.254.1.0/30
  lf2:
    interface: ethernet-1/2
    prefix: 169.254.1.4/30
  lf3:
    interface: ethernet-1/3
    prefix: 169.254.1.8/30
  lf4:
    interface: ethernet-1/4
    prefix: 169.254.1.12/30
  lf5:
    interface: ethernet-1/5
    prefix: 169.254.1.16/30
  lf6:
    interface: ethernet-1/6
    prefix: 169.254.1.20/30
