---
name: 'Python Black linting'
on:
  push:
  pull_request:
jobs:
  black:
    name: 'Run Black on Python code'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: black
        uses: rickstaa/action-black@v1
        with:
          black_args: "*.py --check"
